name: Update iCal Feed

on:
  schedule:
    - cron: '0 11 * * *'    # Every day at 11:00 UTC (change as desired)
  workflow_dispatch:        # Allows you to trigger manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate iCal
        run: |
          python generate_ics.py

      - name: Commit and push iCal file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.ics
          git commit -m "Update iCal file" || echo "No changes to commit"
          git push
